services:
  api:
    build:
      context: ./backend
    environment:
      PYTHONUNBUFFERED: "1"
      # Use the default in-app seeds unless you override via env
      # NARRATIVES_SEEDS_FILE: /app/app/narratives.seeds.json
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      # Critical: frontend will call the API at the service name inside the Compose network
      NEXT_PUBLIC_API_BASE: "http://api:8000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
