version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: primecipher-backend:latest
    ports:
      - "8000:8000"
    environment:
      # SQLite DB path is respected by app.storage/backtest_walk logic
      PRIMECIPHER_DB_PATH: /data/primecipher.db
      PYTHONUNBUFFERED: "1"
      # Optionally point to a custom seeds file inside the container:
      # NARRATIVES_SEEDS_FILE: /app/app/narratives.json
    volumes:
      - primecipher_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  primecipher_data:
    driver: local
