name: CI (backend tests)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache-dependency-path: poetry.lock

      - name: Install Poetry
        run: make bin/poetry/bin/poetry

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install deps (Poetry)
        run: make .venv/bin/activate

      - name: Run pytest
        env:
          PYTHONPATH: .
          PRIMECIPHER_TEST_MODE: "1"
          NARRATIVES_SEEDS_FILE: "../seeds/narratives.seed.json"
        run: make coverage.xml

