name: CI (backend tests)

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/ci.yml"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          else
            # Minimal deps for tests that import adapter/parents
            pip install pytest httpx fastapi uvicorn
          fi

      - name: Run pytest
        working-directory: backend
        run: pytest -q

